# Generated by Django 5.0.3 on 2024-08-05 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_product_countinstock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('image', models.ImageField(upload_to='service_images/')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.service')),
            ],
        ),
    ]
