# Generated by Django 5.0.3 on 2024-09-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wedding_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
