# Generated by Django 5.0.3 on 2024-11-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_review_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shippingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=100.0, max_digits=7, null=True),
        ),
    ]
