# Generated by Django 5.0.3 on 2024-11-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isNotified',
            field=models.BooleanField(default=False),
        ),
    ]
