# Generated by Django 5.0.3 on 2024-11-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_order_isnotified'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
