# Generated by Django 5.0.3 on 2025-01-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_budget_total_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='custom_expenses',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
