# Generated by Django 5.0.3 on 2025-01-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_budget_custom_expenses_alter_budget_total_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='custom_expenses',
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
