# Generated by Django 5.0.3 on 2025-05-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_busyslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusySlot',
        ),
    ]
