# Generated by Django 5.0.3 on 2025-06-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_delete_busyslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isDelivered',
            new_name='markasDone',
        ),
    ]
