# Generated by Django 5.0.3 on 2025-06-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_rename_isdelivered_order_markasdone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isNotified',
            new_name='isCancelled',
        ),
    ]
