# Generated by Django 5.2.4 on 2026-05-13 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_product_facebook_url_product_instagram_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary shown on blog listing (max 300 chars)', max_length=300)),
                ('content', models.TextField(help_text='Full HTML content of the post')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('author', models.CharField(default='WedMangal Team', max_length=100)),
                ('category', models.CharField(choices=[('tamil-weddings', 'Tamil Weddings'), ('wedding-rituals', 'Wedding Rituals'), ('wedding-tips', 'Wedding Tips'), ('vendor-tips', 'Vendor Tips'), ('real-weddings', 'Real Weddings')], default='tamil-weddings', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags e.g. Tamil, Brahmin, Rituals', max_length=300)),
                ('published', models.BooleanField(default=False, help_text='Only published posts appear on the website')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
