# Generated by Django 5.2.4 on 2026-05-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_blog_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='facebook_url',
            new_name='website_url',
        ),
    ]
