# Generated by Django 5.2.4 on 2026-05-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_rename_facebook_url_to_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video_thumb',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
