# Generated by Django 5.2.4 on 2026-05-26 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_add_video_fields_to_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('video_url', models.CharField(max_length=500)),
                ('video_thumb', models.CharField(blank=True, max_length=500, null=True)),
                ('video_duration', models.FloatField(blank=True, null=True)),
                ('video_uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='base.product')),
            ],
            options={
                'ordering': ['order', 'video_uploaded_at'],
            },
        ),
    ]
