# Generated by Django 5.2.4 on 2026-08-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='related_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
