# Generated by Django 5.2.4 on 2026-09-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_blogpost_related_category_blogpost_related_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=13, null=True),
        ),
    ]
