# Generated by Django 5.2.4 on 2026-10-01 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_blogpost_related_category_blogpost_related_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('consent', models.BooleanField(default=False)),
                ('source', models.CharField(default='wedmangal', max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='base.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'created_at'], name='quoterequest_vendor_time')],
            },
        ),
        migrations.CreateModel(
            name='VendorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('vendor_page_view', 'Vendor page view'), ('phone_click', 'Phone click'), ('whatsapp_click', 'WhatsApp click'), ('get_quote_started', 'Get Quote started'), ('get_quote_submitted', 'Get Quote submitted'), ('external_contact_click', 'External contact click'), ('external_booking_click', 'External booking click'), ('search', 'Search'), ('search_result_click', 'Search result click'), ('favorite', 'Favorite'), ('share', 'Share'), ('session_start', 'Session start')], max_length=32)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('path', models.CharField(blank=True, default='', max_length=300)),
                ('referrer', models.CharField(blank=True, default='', max_length=300)),
                ('device_type', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], default='', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_events', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='base.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', 'event_type', 'created_at'], name='vendorevent_vendor_type_time'), models.Index(fields=['event_type', 'created_at'], name='vendorevent_type_time')],
            },
        ),
    ]
