# Generated by Django 5.2.4 on 2026-10-01 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_vendor_events_and_quote_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(choices=[('keyword', 'Search box'), ('filters', 'Filter bar'), ('category', 'Category page filters'), ('search_page', 'Search page')], max_length=20)),
                ('query', models.CharField(blank=True, default='', max_length=200)),
                ('normalized_query', models.CharField(blank=True, default='', max_length=200)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('result_count', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=32, null=True)),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_min', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_max', models.PositiveIntegerField(blank=True, null=True)),
                ('food_preference', models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-vegetarian'), ('both', 'Veg & non-veg')], max_length=10, null=True)),
                ('parking_required', models.BooleanField(blank=True, null=True)),
                ('ac_required', models.BooleanField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'created_at'], name='searchquery_category_time'), models.Index(fields=['area', 'created_at'], name='searchquery_area_time')],
            },
        ),
    ]
