# Generated by Django 5.2.4 on 2026-10-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_search_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='email_status',
            field=models.CharField(blank=True, choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='notification_error',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='sms_status',
            field=models.CharField(blank=True, choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='', max_length=8),
        ),
    ]
