# Generated by Django 5.2.4 on 2026-10-02 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_quote_notification_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_sources',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceownerclaim',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceownerclaim',
            name='method',
            field=models.CharField(blank=True, choices=[('listed_phone_otp', "Code sent to the listing's phone"), ('admin_review', 'Reviewed by WedMangal')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceownerclaim',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceownerclaim',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_owner_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceownerclaim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorevent',
            name='event_type',
            field=models.CharField(choices=[('vendor_page_view', 'Vendor page view'), ('phone_click', 'Phone click'), ('whatsapp_click', 'WhatsApp click'), ('get_quote_started', 'Get Quote started'), ('get_quote_submitted', 'Get Quote submitted'), ('external_contact_click', 'External contact click'), ('external_booking_click', 'External booking click'), ('search', 'Search'), ('search_result_click', 'Search result click'), ('favorite', 'Favorite'), ('share', 'Share'), ('session_start', 'Session start'), ('claim_started', 'Claim started'), ('claim_submitted', 'Claim submitted'), ('claim_approved', 'Claim approved'), ('profile_updated', 'Profile updated')], max_length=32),
        ),
    ]
