# Generated by Django 5.2.4 on 2026-10-04 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_vendor_claim_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='source',
            field=models.CharField(choices=[('keyword', 'Search box'), ('filters', 'Filter bar'), ('category', 'Category page filters'), ('search_page', 'Search page'), ('discovery', 'Discovery questions')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorevent',
            name='event_type',
            field=models.CharField(choices=[('vendor_page_view', 'Vendor page view'), ('phone_click', 'Phone click'), ('whatsapp_click', 'WhatsApp click'), ('get_quote_started', 'Get Quote started'), ('get_quote_submitted', 'Get Quote submitted'), ('external_contact_click', 'External contact click'), ('external_booking_click', 'External booking click'), ('search', 'Search'), ('search_result_click', 'Search result click'), ('favorite', 'Favorite'), ('share', 'Share'), ('session_start', 'Session start'), ('claim_started', 'Claim started'), ('claim_submitted', 'Claim submitted'), ('claim_approved', 'Claim approved'), ('profile_updated', 'Profile updated'), ('discovery_prompt_viewed', 'Discovery prompt viewed'), ('discovery_started', 'Discovery started'), ('discovery_question_answered', 'Discovery question answered'), ('discovery_requirements_completed', 'Discovery requirements completed'), ('discovery_matching_results', 'Discovery matching results'), ('discovery_contact_opened', 'Discovery contact opened'), ('discovery_contact_submitted', 'Discovery contact submitted')], max_length=32),
        ),
        migrations.CreateModel(
            name='DiscoveryLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('category', models.CharField(blank=True, default='', max_length=32)),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('matched', 'Matched with vendors'), ('closed', 'Closed')], default='new', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_leads', to='base.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
