# Generated by Django 5.2.4 on 2026-10-05 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_discovery_leads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorevent',
            name='event_type',
            field=models.CharField(choices=[('vendor_page_view', 'Vendor page view'), ('phone_click', 'Phone click'), ('whatsapp_click', 'WhatsApp click'), ('get_quote_started', 'Get Quote started'), ('get_quote_submitted', 'Get Quote submitted'), ('external_contact_click', 'External contact click'), ('external_booking_click', 'External booking click'), ('search', 'Search'), ('search_result_click', 'Search result click'), ('favorite', 'Favorite'), ('share', 'Share'), ('session_start', 'Session start'), ('claim_started', 'Claim started'), ('claim_submitted', 'Claim submitted'), ('claim_approved', 'Claim approved'), ('profile_updated', 'Profile updated'), ('discovery_prompt_viewed', 'Discovery prompt viewed'), ('discovery_started', 'Discovery started'), ('discovery_question_answered', 'Discovery question answered'), ('discovery_requirements_completed', 'Discovery requirements completed'), ('discovery_matching_results', 'Discovery matching results'), ('discovery_contact_opened', 'Discovery contact opened'), ('discovery_contact_submitted', 'Discovery contact submitted'), ('discovery_budget_opened', 'Discovery budget planner opened'), ('discovery_save_started', 'Discovery save requirements started'), ('budget_saved', 'Budget saved')], max_length=32),
        ),
        migrations.CreateModel(
            name='SavedRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=32)),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_requirements', to='base.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
