# Generated by Django 5.2.4 on 2026-10-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_saved_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='sms_fallback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='whatsapp_request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='whatsapp_status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted by provider'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='whatsapp_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
