# Generated by Django 5.2.4 on 2026-10-08 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_quote_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(db_index=True, max_length=200)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('category_evidence', models.JSONField(blank=True, default=list)),
                ('business_area', models.CharField(blank=True, default='', max_length=150)),
                ('area_status', models.CharField(choices=[('located_in', 'Located in the area'), ('serves', 'Serves the area'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('service_area', models.CharField(blank=True, default='', max_length=150)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('pincode', models.CharField(blank=True, default='', max_length=6)),
                ('area_evidence', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=15)),
                ('website_url', models.URLField(blank=True, default='', max_length=300)),
                ('website_domain', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('source_name', models.CharField(blank=True, default='', max_length=100)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('source_listing_url', models.URLField(blank=True, db_index=True, default='', max_length=500)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('data_source', models.CharField(choices=[('official', 'Official website'), ('directory', 'Directory'), ('google', 'Google'), ('other', 'Other')], default='directory', max_length=10)),
                ('google_place_id', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('research_category', models.CharField(blank=True, default='', max_length=32)),
                ('research_area', models.CharField(blank=True, default='', max_length=150)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('review_count', models.PositiveIntegerField(blank=True, null=True)),
                ('rating_source', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('services', models.JSONField(blank=True, default=list)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('capacity', models.JSONField(blank=True, null=True)),
                ('pricing', models.JSONField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('source_checked', 'Source page fetched and parsed'), ('manually_checked', 'Checked by a person')], default='unverified', max_length=20)),
                ('decision', models.CharField(choices=[('new', 'New'), ('needs_review', 'Needs review'), ('keep', 'Keep'), ('reject', 'Reject'), ('duplicate', 'Duplicate'), ('ready_for_outreach', 'Ready for outreach')], db_index=True, default='new', max_length=20)),
                ('decision_by', models.CharField(default='auto', max_length=10)),
                ('quality_passed', models.BooleanField(db_index=True, default=False)),
                ('quality_score', models.PositiveSmallIntegerField(default=0)),
                ('quality_failures', models.JSONField(blank=True, default=list)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='base.vendorprospect')),
                ('matches_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.product')),
            ],
            options={
                'ordering': ['-quality_score', 'business_name'],
            },
        ),
    ]
